Generate dependabot configuration
google/mono_repo.dart pull request #427
Opened 2023-01-10 10:50 UTC by sigurdm

Fixes: https://github.com/google/mono_repo.dart/issues/374

2023-01-10 21:20 UTC, kevmoo approved these changes

2023-01-10 21:21 UTC, kevmoo requested changes
Actually, please add a changelog entry and double check the version!

2023-01-12 08:39 UTC, sigurdm commented
> Actually, please add a changelog entry and double check the version!

Done!

2023-01-12 19:41 UTC, kevmoo approved these changes

2023-01-12 19:41 UTC, merged